name: Ducksms
targets:
  Ducksms:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Ducksms]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
