//
// PreviewSmsSend.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PreviewSmsSend: Codable { 


    public var status: Int?
    public var message: String?
    public var data: [String:[String]]?

    public init(status: Int?, message: String?, data: [String:[String]]?) {
        self.status = status
        self.message = message
        self.data = data
    }

}
