//
// Sender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Sender: Codable { 


    public enum Status: String, Codable, CaseIterable {
        case active = "active"
        case inactive = "inactive"
    }
    /** Sender name */
    public var name: String?
    /** Sender description */
    public var description: String?
    /** Default sender id */
    public var _default: Bool?
    /** Sender id status */
    public var status: Status?

    public init(name: String?, description: String?, _default: Bool?, status: Status?) {
        self.name = name
        self.description = description
        self._default = _default
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case description
        case _default = "default"
        case status
    }

}
