//
// SmsSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SmsSchema: Codable { 


    public enum Preview: String, Codable, CaseIterable {
        case yes = "yes"
        case no = "no"
    }
    /** Preview the sms information */
    public var preview: Preview?
    public var mobileNumbers: [String]?
    public var message: String?
    public var senderId: String?
    public var scheduledAt: String?
    public var callbackUrl: String?

    public init(preview: Preview?, mobileNumbers: [String]?, message: String?, senderId: String?, scheduledAt: String?, callbackUrl: String?) {
        self.preview = preview
        self.mobileNumbers = mobileNumbers
        self.message = message
        self.senderId = senderId
        self.scheduledAt = scheduledAt
        self.callbackUrl = callbackUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case preview
        case mobileNumbers = "mobile_numbers"
        case message
        case senderId = "sender_id"
        case scheduledAt = "scheduled_at"
        case callbackUrl = "callback_url"
    }

}
