//
// UpdatedSender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UpdatedSender: Codable { 


    public var status: Int?
    public var message: String?
    public var data: [String:Any]?

    public init(status: Int?, message: String?, data: [String:Any]?) {
        self.status = status
        self.message = message
        self.data = data
    }

}
